name: 'Deploy-terraform'
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
jobs:
  variables:
    uses: ./.github/workflows/variables.yml
  build-and-deploy:
    needs: variables
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          enable-AzPSSession: true
   
  plan_dev:
    needs: build-and-deploy
    uses: ./.github/workflows/az_tf_plan.yml
    name: deploy_plan
    with:
      path: 0_All                                     ## Path to terraform root module {{Required}}
      tf_version: latest                              ## Terraform version e.g: 1.1.0 Default=latest {{Optional}}
    secrets: inherit        
