name: 'Deploy-terraform'
on:
  workflow_dispatch:
#   push:
#      branches:
#        - main
jobs:
  variables:
    uses: ./.github/workflows/variables.yml
  build-and-deploy:
    needs: variables
    runs-on: ubuntu-latest
    environment: d
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          enable-AzPSSession: true

      - name: Create Resource Group
        id: create_resource_group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ needs.variables.outputs.az_mgmt_resource_group }} --location ${{ needs.variables.outputs.location }}
  
      - name: Create Storage Account
        id: create_storage_account
        uses: azure/CLI@v1
        with:
            inlineScript: |
              az storage account create --name  ${{ needs.variables.outputs.az_mgmt_storage_acc }} --resource-group  ${{ needs.variables.outputs.az_mgmt_resource_group }} --location  ${{ needs.variables.outputs.location }} --sku Standard_LRS --encryption-services blob
            
      - name: Create Storage Container
        id: create_storage_container
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage container create --name ${{ needs.variables.outputs.az_mgmt_container_name }} --account-name ${{ needs.variables.outputs.az_mgmt_storage_acc }}

  plan_dev:
    needs: build-and-deploy
    uses: ./.github/workflows/az_tf_plan.yml
    name: deploy_plan
    with:
      path: tf_core                                   ## Path to terraform root module {{Required}}
      tf_version: latest                              ## Terraform version e.g: 1.1.0 Default=latest {{Optional}}
    secrets: inherit

  deploy_dev:
    needs: plan_dev
    uses: ./.github/workflows/az_tf_apply.yml
    name: deploy_terraform
    with:
      path: tf_core                                   ## Path to terraform root module {{Required}}
      tf_version: latest                              ## Terraform version e.g: 1.1.0 Default=latest {{Optional}}
    secrets: inherit

