name: Reusable variables

on:
  workflow_call:
    outputs:
      az_mgmt_resource_group:
        description: " AZ backend - AZURE Resource Group hosting terraform backend storage acc"
        value: ${{ jobs.generate_variables.outputs.output1 }}

env:
  az_mgmt_resource_group: "rg-terraform-state"   # AZ backend - AZURE Resource Group hosting terraform backend storage acc

jobs:
  generate_variables:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
    steps:
      - id: step1
        run: echo "firstword=$ {{ env.az_mgmt_resource_group }}" >> $GITHUB_OUTPUT
