variables:
  az_mgmt_resource_group: "rg-terraform-state"   # AZ backend - AZURE Resource Group hosting terraform backend storage acc
  az_mgmt_storage_acc: "stamrictfstates"          # AZ backend - AZURE terraform backend storage acc
  az_mgmt_container_name: "tfstate"                # AZ backend - AZURE storage container hosting state files
  location: "uksouth"                                     # Location for all resources 
  tf_key: "terraform.state"
  tf_vars_file: "config_"
